name: SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      # Install SonarScanner
      - name: Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      # Sonar Begin
      - name: Sonar Begin
        run: |
          dotnet-sonarscanner begin \
            /k:"dranov_ltt-ltc-web-gateway" \
            /o:"dranov" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      # Build
      - name: Build
        run: dotnet build

      # Sonar End
      - name: Sonar End
        run: |
          dotnet-sonarscanner end \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}"